# Generated by Django 3.0.5 on 2022-07-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210510_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='ChemistryMarks',
            new_name='FinalMarks',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='ComputerMarks',
            new_name='HomeworkMarks',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='EnglishMarks',
            new_name='MidtermMarks',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='MathsMarks',
            new_name='ProjectMarks',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='PhysicsMarks',
            new_name='QuizzMarks',
        ),
        migrations.AddField(
            model_name='attendance',
            name='CourseName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
